DROP TABLE H_Visit CASCADE;
DROP TABLE H_Doctor CASCADE;
DROP TABLE H_Speciality CASCADE;
DROP TABLE H_Services CASCADE;
DROP TABLE H_Patient CASCADE;
DROP TABLE H_Doctor CASCADE;

DROP SEQUENCE SEQ_SPEC;
DROP SEQUENCE SEQ_DOC;
DROP SEQUENCE SEQ_srv;
DROP SEQUENCE SEQ_Patient_1;
DROP SEQUENCE SEQ_Patient_2;
DROP SEQUENCE SEQ_Visit;
